import React from 'react';
import { useNavigate } from 'react-router-dom';
import { jsPDF } from 'jspdf';
import { useCurrency } from '../contexts/CurrencyContext';

const SharePreviewScreen: React.FC = () => {
  const navigate = useNavigate();
  const { currencyCode, currencySymbol, formatCurrency } = useCurrency();

  const generateAndSharePDF = async () => {
    const doc = new jsPDF();
    
    // PDF fonts generally don't support INR symbol (₹), so we use a fallback like "Rs." or ISO code for PDF
    const pdfCurrencyPrefix = currencyCode === 'INR' ? 'Rs. ' : currencySymbol;

    // -- Set up basic styles --
    doc.setTextColor(30, 30, 30);
    
    // Header
    doc.setFontSize(22);
    doc.setFont(undefined, 'bold');
    doc.text("WageKeeper", 20, 20);
    
    doc.setFontSize(16);
    doc.setFont(undefined, 'normal');
    doc.text("Salary Slip", 20, 30);
    
    // Period
    doc.setFontSize(10);
    doc.text("Period: Oct 1 - Oct 15, 2023", 190, 20, { align: 'right' });
    
    // Divider
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 35, 190, 35);
    
    // Employee Info
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text("Employee Details", 20, 45);
    
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text("Name: Sarah Jenkins", 20, 52);
    doc.text("Role: Store Manager", 20, 58);
    
    // -- Earnings Section --
    let y = 75;
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text("Earnings", 20, y);
    
    y += 10;
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    
    // Regular
    doc.text("Regular Days", 20, y);
    doc.text(`${pdfCurrencyPrefix}600.00`, 190, y, { align: 'right' });
    y += 5;
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text(`12 days x ${pdfCurrencyPrefix}50.00`, 20, y);
    doc.setTextColor(30);
    
    // Overtime
    y += 10;
    doc.setFontSize(10);
    doc.text("Overtime", 20, y);
    doc.text(`${pdfCurrencyPrefix}50.00`, 190, y, { align: 'right' });
    y += 5;
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text(`5 hours x ${pdfCurrencyPrefix}10.00`, 20, y);
    doc.setTextColor(30);
    
    // Bonus
    y += 10;
    doc.setFontSize(10);
    doc.text("Performance Bonus", 20, y);
    doc.text(`${pdfCurrencyPrefix}25.00`, 190, y, { align: 'right' });
    
    // Divider
    y += 15;
    doc.line(20, y, 190, y);
    
    // -- Deductions Section --
    y += 10;
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text("Deductions", 20, y);
    
    y += 10;
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text("Cash Advance", 20, y);
    doc.setTextColor(220, 50, 50); // Red
    doc.text(`-${pdfCurrencyPrefix}50.00`, 190, y, { align: 'right' });
    doc.setTextColor(30);
    
    // -- Net Pay Section --
    y += 20;
    doc.setFillColor(240, 240, 240); // Light gray box
    doc.rect(20, y - 8, 170, 25, 'F');
    
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(19, 127, 236); // Primary blue
    doc.text("Net Payable", 30, y + 8);
    doc.text(`${pdfCurrencyPrefix}625.00`, 180, y + 8, { align: 'right' });
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.setFont(undefined, 'normal');
    doc.text("Generated by WageKeeper", 105, 280, { align: 'center' });

    // -- Generate & Share --
    const pdfBlob = doc.output('blob');
    const file = new File([pdfBlob], "salary_slip_oct_2023.pdf", { type: "application/pdf" });

    // Use Web Share API if available (acts as Intent on Android)
    if (navigator.share && navigator.canShare({ files: [file] })) {
        try {
            await navigator.share({
                files: [file],
                title: 'Salary Slip - Sarah Jenkins',
                text: 'Here is the salary slip for Oct 1 - Oct 15, 2023.'
            });
        } catch (error) {
            console.log('Error sharing:', error);
        }
    } else {
        // Fallback to direct download
        doc.save("salary_slip_oct_2023.pdf");
    }
  };

  return (
    <div className="font-display bg-background-light dark:bg-background-dark text-[#111418] dark:text-white antialiased h-screen flex flex-col overflow-hidden">
        <header className="flex items-center justify-between px-4 py-3 bg-background-light dark:bg-background-dark z-10 shrink-0">
            <button onClick={() => navigate(-1)} className="p-2 rounded-full hover:bg-black/5 dark:hover:bg-white/10 transition-colors -ml-2">
                <span className="material-symbols-outlined text-[24px]">arrow_back</span>
            </button>
            <h1 className="text-base font-bold tracking-wide">Share Preview</h1>
            <button className="p-2 rounded-full hover:bg-black/5 dark:hover:bg-white/10 transition-colors -mr-2 text-primary font-medium text-sm">Edit</button>
        </header>

        <main className="flex-1 relative flex flex-col items-center justify-start p-6 overflow-y-auto no-scrollbar w-full max-w-md mx-auto">
            <p className="text-sm text-gray-500 dark:text-gray-400 mb-6 text-center">
                This is how the wage summary will look when shared with the employee.
            </p>

            <div className="w-full bg-surface-light dark:bg-surface-dark rounded-3xl shadow-2xl border border-gray-200 dark:border-gray-800 overflow-hidden transform transition-all">
                <div className="px-6 pt-6 pb-4 border-b border-gray-200 dark:border-gray-800/50 flex justify-between items-start">
                    <div>
                        <div className="flex items-center gap-2 mb-1">
                            <div className="w-6 h-6 rounded-md bg-primary flex items-center justify-center text-white">
                                <span className="material-symbols-outlined text-[16px]">account_balance_wallet</span>
                            </div>
                            <span className="text-xs font-bold uppercase tracking-wider text-gray-400">WageKeeper</span>
                        </div>
                        <h2 className="text-xl font-bold text-gray-900 dark:text-white">Wage Statement</h2>
                    </div>
                    <div className="text-right">
                        <p className="text-xs text-gray-500 dark:text-gray-400 uppercase font-semibold">Period</p>
                        <p className="text-sm font-medium text-gray-900 dark:text-gray-200">Oct 1 - Oct 15</p>
                        <p className="text-xs text-gray-400 dark:text-gray-500">2023</p>
                    </div>
                </div>

                <div className="px-6 py-4 bg-gray-50/50 dark:bg-white/[0.02]">
                    <p className="text-xs text-gray-500 dark:text-gray-400 uppercase font-semibold mb-1">Employee</p>
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-full bg-blue-100 dark:bg-blue-900/30 text-primary flex items-center justify-center font-bold text-lg">SJ</div>
                        <div>
                            <p className="text-base font-bold text-gray-900 dark:text-white">Sarah Jenkins</p>
                            <p className="text-xs text-gray-500 dark:text-gray-400">Store Manager</p>
                        </div>
                    </div>
                </div>

                <div className="px-6 py-4 space-y-4">
                    <div className="space-y-3">
                        <p className="text-xs font-bold text-gray-400 uppercase tracking-wider">Earnings</p>
                        <div className="flex justify-between items-center text-sm">
                            <div className="flex flex-col">
                                <span className="text-gray-700 dark:text-gray-300 font-medium">Regular Days</span>
                                <span className="text-xs text-gray-400">12 days × {formatCurrency(50)}</span>
                            </div>
                            <span className="font-semibold text-gray-900 dark:text-white">{formatCurrency(600)}</span>
                        </div>
                        <div className="flex justify-between items-center text-sm">
                            <div className="flex flex-col">
                                <span className="text-gray-700 dark:text-gray-300 font-medium">Overtime</span>
                                <span className="text-xs text-gray-400">5 hours × {formatCurrency(10)}</span>
                            </div>
                            <span className="font-semibold text-gray-900 dark:text-white">{formatCurrency(50)}</span>
                        </div>
                        <div className="flex justify-between items-center text-sm">
                            <span className="text-gray-700 dark:text-gray-300 font-medium">Performance Bonus</span>
                            <span className="font-semibold text-gray-900 dark:text-white">{formatCurrency(25)}</span>
                        </div>
                    </div>

                    <div className="h-px bg-gray-200 dark:bg-gray-800 border-dashed border-b border-gray-300 dark:border-gray-600"></div>

                    <div className="space-y-3">
                        <p className="text-xs font-bold text-gray-400 uppercase tracking-wider">Deductions</p>
                        <div className="flex justify-between items-center text-sm">
                            <div className="flex flex-col">
                                <span className="text-gray-700 dark:text-gray-300 font-medium">Cash Advance</span>
                                <span className="text-xs text-gray-400">Borrowed on Oct 5</span>
                            </div>
                            <span className="font-semibold text-danger">-{formatCurrency(50)}</span>
                        </div>
                    </div>
                </div>

                <div className="bg-primary/5 dark:bg-primary/10 px-6 py-6 border-t border-gray-200 dark:border-gray-800">
                    <div className="flex justify-between items-end">
                        <div className="flex flex-col">
                            <span className="text-sm font-semibold text-gray-500 dark:text-gray-400">Net Payable Wage</span>
                            <span className="text-xs text-gray-400 mt-1">Paid via Cash</span>
                        </div>
                        <span className="text-4xl font-extrabold text-primary tracking-tight">{formatCurrency(625)}</span>
                    </div>
                </div>
            </div>

            <div className="mt-6 flex items-center gap-2 px-4 py-2 bg-yellow-50 dark:bg-yellow-900/20 rounded-lg border border-yellow-100 dark:border-yellow-900/30">
                <span className="material-symbols-outlined text-yellow-600 dark:text-yellow-500 text-lg">info</span>
                <p className="text-xs text-yellow-800 dark:text-yellow-200 leading-snug">
                    The cash advance balance for Sarah will be updated to {formatCurrency(0)} automatically after sharing.
                </p>
            </div>
        </main>

        <div className="p-4 bg-surface-light dark:bg-background-dark border-t border-gray-200 dark:border-gray-800 shrink-0 pb-8">
            <div className="grid grid-cols-5 gap-3 max-w-md mx-auto">
                <button onClick={generateAndSharePDF} className="col-span-1 flex items-center justify-center aspect-square rounded-xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-surface-dark text-gray-700 dark:text-gray-200 hover:bg-gray-50 dark:hover:bg-white/5 transition-colors">
                    <span className="material-symbols-outlined">download</span>
                </button>
                <button onClick={generateAndSharePDF} className="col-span-4 flex items-center justify-center gap-2 rounded-xl bg-primary hover:bg-primary-dark text-white font-semibold text-base shadow-lg shadow-blue-500/30 transition-all active:scale-[0.98]">
                    <span className="material-symbols-outlined">share</span>
                    Share Summary
                </button>
            </div>
        </div>
    </div>
  );
};

export default SharePreviewScreen;
